# Generated by Django 3.2.16 on 2024-07-31 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_desciption_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='title',
            new_name='name',
        ),
    ]
